### ISSUE TITLE
Meetup - Polkadot - Seville, Spain

### ISSUE THREAD

**Issue by wimel** [w3f/Web3-collaboration#132]
Since 2015 we have an [Ethereum meetup](https://www.meetup.com/es-ES/Ethereum-Meetup-Sevilla/) doing One meetup per quarter, and recently One per month, with the arrival of PoS and several interesting projects we usually give workshops with another [meetup about PoS](https://www.meetup.com/es-ES/Proof-Of-Stake-SvQ/) where people can learn by doing things, in our group we have a [systems administrator](https://github.com/derfredy) with long experience, a person with [experience in frontend](https://github.com/anagutjor) and a [passionate about blockchain](https://github.com/wimel), we have our [own space](https://www.coworkingcolmena.com) with no company behind, from users to users. We are also part of the Polkadot network since the first testnet, actually with several nodes =)
The meetup collaborators are part of the [community of developers](https://sevilladevelopers.github.io) in Seville (SvQTech & SvQDev)

**Plan:** Teach people by focusing on technology and practical use cases

**How many people:** More or less we tend to be about 20

**Help from W3F:**  Bringing speakers to our city would be the best, workshops or hackathons too, and of course and if possible some merchandising

**Help from community:** It would be good to join forces with our colleagues in Spain to make something together.

**Comment by Web3Foundation** [comment]
@wimel this looks great, could you also apply through https://polkadot.network/launching-worldwide-polkadot-web3-community-meetups/ so we can make sure you're taken care of in the correct fashion! :)

**Comment by Web3Foundation** [comment]
Following up via alternative routes; @wimel is an ambassador and working on this.

**Comment by wimel** [comment]
Close the ISSUE, thanks for the help!!
