### ISSUE TITLE
Tucson Polkadot Fishermans Cooperative - Tucson, Arizona USA

### ISSUE THREAD

**Issue by tucsonblockchain** [w3f/Web3-collaboration#24]
Looking  to establish Tucson Polkadot Fishermans Cooperative. Starting as self sovereign ID, moving to Meetup and onto cooperative if not united cooperative among many.....

**Comment by EdwardAThomson** [comment]
Going to suggested pushing this towards Riot or to our forum:

https://forum.web3.foundation/
