### ISSUE TITLE
Polkadot Beginners Lounge working document

### ISSUE THREAD

**Issue by tucsonblockchain** [w3f/Web3-collaboration#25]
Coinciding with the "Riot" Polkadot Beginners Lounge is the working document (feel free to edit working document if relevant to Polkadot or helpful to beginners)!
https://docs.google.com/document/d/1SNey7jheZrFk-r977_qgFDah7OcjBYMH3O5TfbDZWJI/edit?usp=sharing

**Comment by EdwardAThomson** [comment]
Will also recommend moving this to Riot or the new forum: https://forum.web3.foundation
