### ISSUE TITLE
Videos explaining Polkadot

### ISSUE THREAD

**Issue by jplatts12** [w3f/Web3-collaboration#35]
Polkadot needs more videos! These can be short webcam explainer videos or creative animations of how certain components and features of the protocol works. Have fun with this!

**Comment by EdwardAThomson** [comment]
Current videos:

* Gavin Wood presents on [Polkadot at Ethereum London (June 2017)](https://www.youtube.com/watch?v=lIghiCmHz0U)
* Gavin Wood presents [Parity Substrate at EventHorizon18 (Berlin)](https://www.youtube.com/watch?v=iUMZyL5kTwc)
  * The slides: https://slides.com/paritytech/paritysubstrate#/  
* Gavin Wood presents [Substrate and Polkadot Governance at EdCon (Toronto)](https://www.youtube.com/watch?v=VsZuDJMmVPY&t=24735s&list=PL6-IF807eaBG5sH-SQXlosqKRM2BZkrqw&index=4)
  * Slides: https://slides.com/paritytech/polkadot-governance#/
* Robert Habermeier also presented [Parity Substrate at the Berlin Truebit Meetup]( https://www.youtube.com/watch?v=q1zLHO7Lkuk)

Note that Substrate is an example of a [Polkadot Runtime Environment](https://github.com/w3f/Web3-wiki/wiki/Polkadot-Runtime-Environment) created by Parity Technologies.
