### ISSUE TITLE
Meetup - Polkadot - Korea

### ISSUE THREAD

**Issue by trustfarm-dev** [w3f/Web3-collaboration#41]
Dear all,

Here's great support and promote polkadot in Korea.

I'm very pleased with Polkadot and Web3 . if I choosed with participates for tour by Polkadot community.

If You need Korea local meetup and organization branch, I'll do my best.
Great Tour until end of 2018.

**Comment by EdwardAThomson** [comment]
Hey Trustfarm, many thanks for your continued interested. I appreciate you opening an issue here too. Just an FYI, we do have an issue for Seoul already, but I'm happy to have a separate issue if that helps people to coordinate in other areas of Korea. :-)

See here: https://github.com/w3f/Web3-collaboration/issues/4

There is a meetup.com group for Seoul already too: https://www.meetup.com/Polkadot-Seoul/

**Comment by trustfarm-dev** [comment]
I think they have many polkadot Meetup allocated.
So I wondering they are not official consensus with polkadot.

**Comment by EdwardAThomson** [comment]
The official meetup groups can be found at the following link: https://www.meetup.com/pro/polkadot/

**Comment by trustfarm-dev** [comment]
Above Meetup link is officially maintained by web3 and polkadot foundation?
It is clearly confirmed then I will cancel the Meetup organization in Korea.

**Comment by EdwardAThomson** [comment]
We do still need help with local people in Korea. The closer we can work with local people the better the outcome of the events. We really need the local knowledge to find the best venues and help to connect with the right groups to make the event successful. :-)

So there is definitely help needed for Korea.

**Comment by trustfarm-dev** [comment]
@EdwardAThomson  I'm sorry, If you concern above official meetup organizer, Not Me.
