### ISSUE TITLE
minor issue in PR form

### ISSUE THREAD

**Issue by SCBuergel** [w3f/Web3-collaboration#53]
While filling in the form of the PR I found some minor issues:

1. The PR form is stating `- [x] The application is being included into the correct directory: either '[programmes](https://github.com/w3f/Web3-collaboration/grants//tree/master/grants/programmes)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.` The former link is dead and should probably be replaced by `https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted`
2. The PR form asks me to confirm that `- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) has been completed accurately.`. This creates a circular dependency as the Google Form requires a link to the PR. (I was cheating / assuming you meant "The Google Form **will** be completed accurately." ;-)

**Comment by EdwardAThomson** [comment]
Thanks!

  1. Was a reworded along the way. Will update this soon!
  1. Thanks! Perhaps the wording here could be better!

:-)
