### ISSUE TITLE
Link is not working: 404 error

### ISSUE THREAD

**Issue by pkrasam** [w3f/Web3-collaboration#57]
https://github.com/w3f/Web3-collaboration/blob/master/.github/PULL_REQUEST_TEMPLATE/grant_application.md

**Comment by EdwardAThomson** [comment]
Thanks!

Yeah. That's the wrong link. For some reason I must have included the wrong link in the grants.md page. I honestly thought I only had working links on that page.

However, I've fixed this issue now!


The pull request template is here:  https://github.com/w3f/Web3-collaboration/blob/master/.github/PULL_REQUEST_TEMPLATE.md

The application template is here: https://github.com/w3f/Web3-collaboration/blob/master/grants/grant_application_template.md
